services:
  - type: web
    name: css-creator
    runtime: php
    buildCommand: ""
    startCommand: php -S 0.0.0.0:$PORT
    envVars:
      - key: PHP_VERSION
        value: 8.2
    healthCheckPath: /
    autoDeploy: true
